[2021-02-22 17:52:55,452] {scheduler_job.py:182} INFO - Started process (PID=47) to work on /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 17:52:55,464] {scheduler_job.py:633} INFO - Processing file /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py for tasks to queue
[2021-02-22 17:52:55,467] {logging_mixin.py:104} INFO - [2021-02-22 17:52:55,466] {dagbag.py:448} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 17:52:55,543] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['example_dag_decorator']) retrieved from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 17:52:55,569] {logging_mixin.py:104} INFO - [2021-02-22 17:52:55,569] {dag.py:1818} INFO - Sync 1 DAGs
[2021-02-22 17:52:55,579] {logging_mixin.py:104} INFO - [2021-02-22 17:52:55,579] {dag.py:1837} INFO - Creating ORM DAG for example_dag_decorator
[2021-02-22 17:52:55,586] {logging_mixin.py:104} INFO - [2021-02-22 17:52:55,586] {dag.py:2273} INFO - Setting next_dagrun for example_dag_decorator to None
[2021-02-22 17:52:55,603] {scheduler_job.py:190} INFO - Processing /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py took 0.154 seconds
[2021-02-22 17:53:37,411] {scheduler_job.py:182} INFO - Started process (PID=75) to work on /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 17:53:37,413] {scheduler_job.py:633} INFO - Processing file /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py for tasks to queue
[2021-02-22 17:53:37,414] {logging_mixin.py:104} INFO - [2021-02-22 17:53:37,414] {dagbag.py:448} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 17:53:37,854] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['example_dag_decorator']) retrieved from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 17:53:37,882] {logging_mixin.py:104} INFO - [2021-02-22 17:53:37,882] {dag.py:1818} INFO - Sync 1 DAGs
[2021-02-22 17:53:37,901] {logging_mixin.py:104} INFO - [2021-02-22 17:53:37,901] {dag.py:2273} INFO - Setting next_dagrun for example_dag_decorator to None
[2021-02-22 17:53:38,113] {scheduler_job.py:190} INFO - Processing /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py took 0.704 seconds
[2021-02-22 17:54:21,269] {scheduler_job.py:182} INFO - Started process (PID=37) to work on /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 17:54:21,273] {scheduler_job.py:633} INFO - Processing file /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py for tasks to queue
[2021-02-22 17:54:21,275] {logging_mixin.py:104} INFO - [2021-02-22 17:54:21,275] {dagbag.py:448} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 17:54:21,330] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['example_dag_decorator']) retrieved from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 17:54:21,409] {logging_mixin.py:104} INFO - [2021-02-22 17:54:21,408] {dag.py:1818} INFO - Sync 1 DAGs
[2021-02-22 17:54:21,445] {logging_mixin.py:104} INFO - [2021-02-22 17:54:21,444] {dag.py:2273} INFO - Setting next_dagrun for example_dag_decorator to None
[2021-02-22 17:54:21,460] {scheduler_job.py:190} INFO - Processing /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py took 0.205 seconds
[2021-02-22 17:54:52,361] {scheduler_job.py:182} INFO - Started process (PID=64) to work on /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 17:54:52,364] {scheduler_job.py:633} INFO - Processing file /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py for tasks to queue
[2021-02-22 17:54:52,366] {logging_mixin.py:104} INFO - [2021-02-22 17:54:52,366] {dagbag.py:448} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 17:54:52,437] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['example_dag_decorator']) retrieved from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 17:54:52,497] {logging_mixin.py:104} INFO - [2021-02-22 17:54:52,497] {dag.py:1818} INFO - Sync 1 DAGs
[2021-02-22 17:54:52,517] {logging_mixin.py:104} INFO - [2021-02-22 17:54:52,517] {dag.py:2273} INFO - Setting next_dagrun for example_dag_decorator to None
[2021-02-22 17:54:52,540] {scheduler_job.py:190} INFO - Processing /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py took 0.183 seconds
[2021-02-22 17:55:27,672] {scheduler_job.py:182} INFO - Started process (PID=93) to work on /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 17:55:27,674] {scheduler_job.py:633} INFO - Processing file /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py for tasks to queue
[2021-02-22 17:55:27,678] {logging_mixin.py:104} INFO - [2021-02-22 17:55:27,677] {dagbag.py:448} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 17:55:27,830] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['example_dag_decorator']) retrieved from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 17:55:27,873] {logging_mixin.py:104} INFO - [2021-02-22 17:55:27,873] {dag.py:1818} INFO - Sync 1 DAGs
[2021-02-22 17:55:27,890] {logging_mixin.py:104} INFO - [2021-02-22 17:55:27,890] {dag.py:2273} INFO - Setting next_dagrun for example_dag_decorator to None
[2021-02-22 17:55:27,917] {scheduler_job.py:190} INFO - Processing /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py took 0.249 seconds
[2021-02-22 17:55:59,521] {scheduler_job.py:182} INFO - Started process (PID=121) to work on /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 17:55:59,523] {scheduler_job.py:633} INFO - Processing file /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py for tasks to queue
[2021-02-22 17:55:59,525] {logging_mixin.py:104} INFO - [2021-02-22 17:55:59,524] {dagbag.py:448} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 17:55:59,558] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['example_dag_decorator']) retrieved from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 17:55:59,607] {logging_mixin.py:104} INFO - [2021-02-22 17:55:59,607] {dag.py:1818} INFO - Sync 1 DAGs
[2021-02-22 17:55:59,624] {logging_mixin.py:104} INFO - [2021-02-22 17:55:59,624] {dag.py:2273} INFO - Setting next_dagrun for example_dag_decorator to None
[2021-02-22 17:55:59,665] {scheduler_job.py:190} INFO - Processing /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py took 0.148 seconds
[2021-02-22 18:03:22,836] {scheduler_job.py:182} INFO - Started process (PID=32) to work on /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:03:22,839] {scheduler_job.py:633} INFO - Processing file /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py for tasks to queue
[2021-02-22 18:03:22,841] {logging_mixin.py:104} INFO - [2021-02-22 18:03:22,841] {dagbag.py:448} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:03:22,996] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['example_dag_decorator']) retrieved from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:03:23,060] {logging_mixin.py:104} INFO - [2021-02-22 18:03:23,060] {dag.py:1818} INFO - Sync 1 DAGs
[2021-02-22 18:03:23,098] {logging_mixin.py:104} INFO - [2021-02-22 18:03:23,097] {dag.py:2273} INFO - Setting next_dagrun for example_dag_decorator to None
[2021-02-22 18:03:23,131] {scheduler_job.py:190} INFO - Processing /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py took 0.304 seconds
[2021-02-22 18:03:53,937] {scheduler_job.py:182} INFO - Started process (PID=61) to work on /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:03:53,939] {scheduler_job.py:633} INFO - Processing file /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py for tasks to queue
[2021-02-22 18:03:53,941] {logging_mixin.py:104} INFO - [2021-02-22 18:03:53,941] {dagbag.py:448} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:03:54,004] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['example_dag_decorator']) retrieved from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:03:54,040] {logging_mixin.py:104} INFO - [2021-02-22 18:03:54,040] {dag.py:1818} INFO - Sync 1 DAGs
[2021-02-22 18:03:54,060] {logging_mixin.py:104} INFO - [2021-02-22 18:03:54,060] {dag.py:2273} INFO - Setting next_dagrun for example_dag_decorator to None
[2021-02-22 18:03:54,079] {scheduler_job.py:190} INFO - Processing /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py took 0.145 seconds
[2021-02-22 18:04:31,617] {scheduler_job.py:182} INFO - Started process (PID=88) to work on /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:04:31,620] {scheduler_job.py:633} INFO - Processing file /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py for tasks to queue
[2021-02-22 18:04:31,622] {logging_mixin.py:104} INFO - [2021-02-22 18:04:31,621] {dagbag.py:448} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:04:31,746] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['example_dag_decorator']) retrieved from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:04:31,828] {logging_mixin.py:104} INFO - [2021-02-22 18:04:31,828] {dag.py:1818} INFO - Sync 1 DAGs
[2021-02-22 18:04:31,847] {logging_mixin.py:104} INFO - [2021-02-22 18:04:31,847] {dag.py:2273} INFO - Setting next_dagrun for example_dag_decorator to None
[2021-02-22 18:04:31,883] {scheduler_job.py:190} INFO - Processing /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py took 0.271 seconds
[2021-02-22 18:05:02,400] {scheduler_job.py:182} INFO - Started process (PID=118) to work on /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:05:02,401] {scheduler_job.py:633} INFO - Processing file /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py for tasks to queue
[2021-02-22 18:05:02,403] {logging_mixin.py:104} INFO - [2021-02-22 18:05:02,403] {dagbag.py:448} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:05:02,418] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['example_dag_decorator']) retrieved from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:05:02,444] {logging_mixin.py:104} INFO - [2021-02-22 18:05:02,444] {dag.py:1818} INFO - Sync 1 DAGs
[2021-02-22 18:05:02,459] {logging_mixin.py:104} INFO - [2021-02-22 18:05:02,459] {dag.py:2273} INFO - Setting next_dagrun for example_dag_decorator to None
[2021-02-22 18:05:02,470] {scheduler_job.py:190} INFO - Processing /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py took 0.074 seconds
[2021-02-22 18:05:47,165] {scheduler_job.py:182} INFO - Started process (PID=41) to work on /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:05:47,167] {scheduler_job.py:633} INFO - Processing file /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py for tasks to queue
[2021-02-22 18:05:47,169] {logging_mixin.py:104} INFO - [2021-02-22 18:05:47,169] {dagbag.py:448} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:05:47,192] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['example_dag_decorator']) retrieved from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:05:47,242] {logging_mixin.py:104} INFO - [2021-02-22 18:05:47,241] {dag.py:1818} INFO - Sync 1 DAGs
[2021-02-22 18:05:47,282] {logging_mixin.py:104} INFO - [2021-02-22 18:05:47,282] {dag.py:2273} INFO - Setting next_dagrun for example_dag_decorator to None
[2021-02-22 18:05:47,364] {scheduler_job.py:190} INFO - Processing /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py took 0.202 seconds
[2021-02-22 18:06:25,325] {scheduler_job.py:182} INFO - Started process (PID=68) to work on /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:06:25,358] {scheduler_job.py:633} INFO - Processing file /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py for tasks to queue
[2021-02-22 18:06:25,441] {logging_mixin.py:104} INFO - [2021-02-22 18:06:25,441] {dagbag.py:448} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:06:26,113] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['example_dag_decorator']) retrieved from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:06:26,216] {logging_mixin.py:104} INFO - [2021-02-22 18:06:26,216] {dag.py:1818} INFO - Sync 1 DAGs
[2021-02-22 18:06:26,306] {logging_mixin.py:104} INFO - [2021-02-22 18:06:26,306] {dag.py:2273} INFO - Setting next_dagrun for example_dag_decorator to None
[2021-02-22 18:06:26,360] {scheduler_job.py:190} INFO - Processing /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py took 1.041 seconds
[2021-02-22 18:07:02,610] {scheduler_job.py:182} INFO - Started process (PID=96) to work on /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:07:02,613] {scheduler_job.py:633} INFO - Processing file /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py for tasks to queue
[2021-02-22 18:07:02,615] {logging_mixin.py:104} INFO - [2021-02-22 18:07:02,615] {dagbag.py:448} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:07:02,759] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['example_dag_decorator']) retrieved from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:07:02,784] {logging_mixin.py:104} INFO - [2021-02-22 18:07:02,784] {dag.py:1818} INFO - Sync 1 DAGs
[2021-02-22 18:07:02,804] {logging_mixin.py:104} INFO - [2021-02-22 18:07:02,802] {dag.py:2273} INFO - Setting next_dagrun for example_dag_decorator to None
[2021-02-22 18:07:02,960] {scheduler_job.py:190} INFO - Processing /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py took 0.356 seconds
[2021-02-22 18:08:18,717] {scheduler_job.py:182} INFO - Started process (PID=36) to work on /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:08:18,720] {scheduler_job.py:633} INFO - Processing file /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py for tasks to queue
[2021-02-22 18:08:18,722] {logging_mixin.py:104} INFO - [2021-02-22 18:08:18,722] {dagbag.py:448} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:08:18,782] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['example_dag_decorator']) retrieved from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:08:18,860] {logging_mixin.py:104} INFO - [2021-02-22 18:08:18,860] {dag.py:1818} INFO - Sync 1 DAGs
[2021-02-22 18:08:18,881] {logging_mixin.py:104} INFO - [2021-02-22 18:08:18,881] {dag.py:2273} INFO - Setting next_dagrun for example_dag_decorator to None
[2021-02-22 18:08:18,962] {scheduler_job.py:190} INFO - Processing /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py took 0.257 seconds
[2021-02-22 18:08:54,617] {scheduler_job.py:182} INFO - Started process (PID=64) to work on /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:08:54,639] {scheduler_job.py:633} INFO - Processing file /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py for tasks to queue
[2021-02-22 18:08:54,643] {logging_mixin.py:104} INFO - [2021-02-22 18:08:54,642] {dagbag.py:448} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:08:54,791] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['example_dag_decorator']) retrieved from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:08:54,865] {logging_mixin.py:104} INFO - [2021-02-22 18:08:54,865] {dag.py:1818} INFO - Sync 1 DAGs
[2021-02-22 18:08:54,883] {logging_mixin.py:104} INFO - [2021-02-22 18:08:54,883] {dag.py:2273} INFO - Setting next_dagrun for example_dag_decorator to None
[2021-02-22 18:08:54,918] {scheduler_job.py:190} INFO - Processing /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py took 0.308 seconds
[2021-02-22 18:09:25,344] {scheduler_job.py:182} INFO - Started process (PID=91) to work on /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:09:25,346] {scheduler_job.py:633} INFO - Processing file /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py for tasks to queue
[2021-02-22 18:09:25,347] {logging_mixin.py:104} INFO - [2021-02-22 18:09:25,347] {dagbag.py:448} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:09:25,429] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['example_dag_decorator']) retrieved from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:09:25,453] {logging_mixin.py:104} INFO - [2021-02-22 18:09:25,453] {dag.py:1818} INFO - Sync 1 DAGs
[2021-02-22 18:09:25,468] {logging_mixin.py:104} INFO - [2021-02-22 18:09:25,468] {dag.py:2273} INFO - Setting next_dagrun for example_dag_decorator to None
[2021-02-22 18:09:25,486] {scheduler_job.py:190} INFO - Processing /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py took 0.145 seconds
[2021-02-22 18:10:06,381] {logging_mixin.py:104} INFO - [2021-02-22 18:10:06,381] {process_utils.py:206} INFO - Waiting up to 5 seconds for processes to exit...
[2021-02-22 18:10:06,396] {scheduler_job.py:193} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/scheduler/2021-02-22/native_dags/example_dags/example_dag_decorator.py.log'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/scheduler_job.py", line 175, in _run_file_processor
    settings.configure_orm()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py", line 222, in configure_orm
    engine = create_engine(SQL_ALCHEMY_CONN, connect_args=connect_args, **engine_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/__init__.py", line 520, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 191, in create
    event.listen(pool, "first_connect", on_connect)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/event/api.py", line 102, in listen
    _event_key(target, identifier, fn).listen(*args, **kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/event/api.py", line 25, in _event_key
    tgt = evt_cls._accept_with(target)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_processing.py", line 574, in _exit_gracefully
    self.end()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_processing.py", line 1147, in end
    kill_child_processes_by_pids(pids_to_kill)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/process_utils.py", line 206, in kill_child_processes_by_pids
    log.info("Waiting up to %s seconds for processes to exit...", timeout)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1442, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_processing.py", line 574, in _exit_gracefully
    self.end()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_processing.py", line 1147, in end
    kill_child_processes_by_pids(pids_to_kill)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/process_utils.py", line 206, in kill_child_processes_by_pids
    log.info("Waiting up to %s seconds for processes to exit...", timeout)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1442, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1002, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 116, in write
    self._propagate_log(self._buffer.rstrip())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 104, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1508, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 67, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
RecursionError: maximum recursion depth exceeded
[2021-02-22 18:12:26,886] {scheduler_job.py:182} INFO - Started process (PID=28) to work on /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:12:26,893] {scheduler_job.py:633} INFO - Processing file /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py for tasks to queue
[2021-02-22 18:12:26,895] {logging_mixin.py:104} INFO - [2021-02-22 18:12:26,894] {dagbag.py:448} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:12:26,923] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['example_dag_decorator']) retrieved from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:12:26,982] {logging_mixin.py:104} INFO - [2021-02-22 18:12:26,981] {dag.py:1818} INFO - Sync 1 DAGs
[2021-02-22 18:12:27,006] {logging_mixin.py:104} INFO - [2021-02-22 18:12:27,005] {dag.py:2273} INFO - Setting next_dagrun for example_dag_decorator to None
[2021-02-22 18:12:27,037] {scheduler_job.py:190} INFO - Processing /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py took 0.155 seconds
[2021-02-22 18:12:57,190] {scheduler_job.py:182} INFO - Started process (PID=56) to work on /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:12:57,192] {scheduler_job.py:633} INFO - Processing file /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py for tasks to queue
[2021-02-22 18:12:57,194] {logging_mixin.py:104} INFO - [2021-02-22 18:12:57,194] {dagbag.py:448} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:12:57,253] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['example_dag_decorator']) retrieved from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:12:57,293] {logging_mixin.py:104} INFO - [2021-02-22 18:12:57,293] {dag.py:1818} INFO - Sync 1 DAGs
[2021-02-22 18:12:57,311] {logging_mixin.py:104} INFO - [2021-02-22 18:12:57,311] {dag.py:2273} INFO - Setting next_dagrun for example_dag_decorator to None
[2021-02-22 18:12:57,328] {scheduler_job.py:190} INFO - Processing /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py took 0.143 seconds
[2021-02-22 18:13:34,907] {scheduler_job.py:182} INFO - Started process (PID=84) to work on /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:13:34,910] {scheduler_job.py:633} INFO - Processing file /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py for tasks to queue
[2021-02-22 18:13:34,912] {logging_mixin.py:104} INFO - [2021-02-22 18:13:34,912] {dagbag.py:448} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:13:35,168] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['example_dag_decorator']) retrieved from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:13:35,205] {logging_mixin.py:104} INFO - [2021-02-22 18:13:35,205] {dag.py:1818} INFO - Sync 1 DAGs
[2021-02-22 18:13:35,220] {logging_mixin.py:104} INFO - [2021-02-22 18:13:35,220] {dag.py:2273} INFO - Setting next_dagrun for example_dag_decorator to None
[2021-02-22 18:13:35,245] {scheduler_job.py:190} INFO - Processing /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py took 0.341 seconds
[2021-02-22 18:14:07,846] {scheduler_job.py:182} INFO - Started process (PID=112) to work on /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:14:07,848] {scheduler_job.py:633} INFO - Processing file /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py for tasks to queue
[2021-02-22 18:14:07,850] {logging_mixin.py:104} INFO - [2021-02-22 18:14:07,850] {dagbag.py:448} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:14:07,909] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['example_dag_decorator']) retrieved from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:14:07,968] {logging_mixin.py:104} INFO - [2021-02-22 18:14:07,968] {dag.py:1818} INFO - Sync 1 DAGs
[2021-02-22 18:14:07,994] {logging_mixin.py:104} INFO - [2021-02-22 18:14:07,994] {dag.py:2273} INFO - Setting next_dagrun for example_dag_decorator to None
[2021-02-22 18:14:08,030] {scheduler_job.py:190} INFO - Processing /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py took 0.189 seconds
[2021-02-22 18:17:45,143] {scheduler_job.py:182} INFO - Started process (PID=32) to work on /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:17:45,145] {scheduler_job.py:633} INFO - Processing file /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py for tasks to queue
[2021-02-22 18:17:45,148] {logging_mixin.py:104} INFO - [2021-02-22 18:17:45,148] {dagbag.py:448} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:17:45,245] {scheduler_job.py:643} INFO - DAG(s) dict_keys(['example_dag_decorator']) retrieved from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py
[2021-02-22 18:17:45,294] {logging_mixin.py:104} INFO - [2021-02-22 18:17:45,294] {dag.py:1818} INFO - Sync 1 DAGs
[2021-02-22 18:17:45,328] {logging_mixin.py:104} INFO - [2021-02-22 18:17:45,328] {dag.py:2273} INFO - Setting next_dagrun for example_dag_decorator to None
[2021-02-22 18:17:45,363] {scheduler_job.py:190} INFO - Processing /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/example_dag_decorator.py took 0.235 seconds
